architect:
  - volodya-lombrozo
docker:
  image: yegor256/rultor-image:1.23.1
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
merge:
  script: mvn clean install -Pqulice --errors --batch-mode
release:
  pre: false
  script: |-
    echo "Master branch"
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" 
    git commit -am "${tag}"
    mvn clean install -Pqulice --errors --batch-mode -Dinvoker.skip -DskipITs
    mvn clean deploy -Pobjectionary -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
