/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.jeo;

import com.jcabi.log.Logger;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.Collections;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Bytecode classes verifier.
 *
 * <p>This class knows how to verify generated bytecode. It performs comprehensive
 * verification of bytecode files using ASM's analysis framework. It requires all
 * the classes to be loaded into the current classloader. See {@link PluginStartup#init()}
 * for details on how all generated classes are loaded.</p>
 * @since 0.6.0
 */
final class BytecodeClasses implements Classes {

    /**
     * Input directory where all the generated class files are placed.
     */
    private final Path input;

    /**
     * Constructor with filters.
     * @param input Input directory where all the generated class files are placed.
     */
    BytecodeClasses(final Path input) {
        this.input = input;
    }

    @Override
    public String toString() {
        return this.input.toString();
    }

    @Override
    public long total() {
        return this.all().count();
    }

    @Override
    public Path root() {
        return this.input;
    }

    @Override
    public Stream<Path> all() {
        try {
            return this.classes().stream();
        } catch (final IOException exception) {
            throw new IllegalStateException(
                String.format(
                    "Can't read '%s' directory with classes",
                    this.input
                ),
                exception
            );
        }
    }

    /**
     * Verify bytecode in the folder.
     */
    void verify() {
        this.all().forEach(BytecodeClasses::verify);
    }

    /**
     * Find all bytecode files.
     * @return Collection of bytecode files
     * @throws IOException If some I/O problem arises
     */
    private Collection<Path> classes() throws IOException {
        if (Objects.isNull(this.input)) {
            throw new IllegalStateException(
                "The classes directory is not set, jeo-maven-plugin does not know where to look for classes."
            );
        }
        final Collection<Path> result;
        if (Files.exists(this.input)) {
            try (Stream<Path> walk = Files.walk(this.input)) {
                result = walk
                    .filter(Files::isRegularFile)
                    .filter(path -> path.toString().endsWith(".class"))
                    .collect(Collectors.toList());
            }
        } else {
            Logger.warn(
                this,
                String.format(
                    "The classes directory '%s' does not exist, jeo-maven-plugin does not know where to look for classes.",
                    this.input
                )
            );
            result = Collections.emptyList();
        }
        return result;
    }

    /**
     * Read bytes of the class file.
     * @param clazz Path to the class file to read
     * @return Bytes of the class file
     */
    private static byte[] read(final Path clazz) {
        try {
            return Files.readAllBytes(clazz);
        } catch (final IOException exception) {
            throw new IllegalStateException(
                String.format("Can't read bytecode from the file '%s'", clazz),
                exception
            );
        }
    }

    /**
     * Verify the bytecode of the class file.
     * @param clazz Path to the class file to verify
     */
    private static void verify(final Path clazz) {
        final byte[] bytes = BytecodeClasses.read(clazz);
        try {
            new VerifiedBytecode(bytes).verify();
        } catch (final IllegalArgumentException exception) {
            throw new IllegalArgumentException(
                String.format("Invalid bytecode of class '%s'", clazz), exception
            );
        }
    }
}
