# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: verify
on:
  schedule:
    - cron: "0 2 * * *"   # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        java: [ 23 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}
            -jdk-${{ matrix.java }}
            -maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: mvn clean install -D"skipTests" -P"verify" --errors --batch-mode
