# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: phino
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: phino-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: objectionary/phino@f69bd2d22499767f050bd84edd697d9b9ea929aa  # master
        with:
          version: 0.0.0.67
      - run: mvn clean install -ntp -D"skipTests" -D"invoker.test=phi-unphi" --errors --batch-mode
